#!/usr/bin/env bash

files=$(find /vms/clusters/variables-files/ -type f -exec basename {} \; | sed 's/^ansible-vars-//' | sed 's/\.json$//')

selected_file=$(echo "$files" | sort | fzf-tmux --header=$'Select a variable file:\n\n' --layout=reverse  -h 40 -p "15%,20%" --exact)

if [ -n "$selected_file" ]; then
    tmux new-window -n "vim /vms/clusters/variables-files/ansible-vars-$selected_file.json" "vim /vms/clusters/variables-files/ansible-vars-$selected_file.json; tmux wait-for -S vim-done"
    tmux wait-for vim-done

    temp_file=$(mktemp)

    tmux new-window -n "create cluster" "bash -c 'read -p \"Are you sure you want to create the cluster? (y/N): \" confirm; echo \$confirm > $temp_file; bash'"

    while [ ! -s "$temp_file" ]; do
      sleep 1
    done

    confirm=$(cat "$temp_file")
    rm -f "$temp_file"

    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
      exit 0
    fi

    tmux send-keys "/usr/local/bin/createcluster.py -i /vms/clusters/variables-files/ansible-vars-$selected_file.json" C-m

else
#    tmux display -d 3000 "No file selected"
    exit 0
fi




