#!/bin/bash

clusters() {
  local dir="$1"
  FOLDER_VMWARE="/CHIARETTO/vm/$1"
  VMMASTER0=$(govc ls "${FOLDER_VMWARE}" | grep "master-0")
  VMMASTER0STATE=$(govc vm.info -json "$VMMASTER0" | jq -r '.virtualMachines[0].runtime.powerState')
  vmwarenotes=$(jq -r '.vmwarenotes' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
  ocpversion=$(jq -r '.ocpversion' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
  if [ "$VMMASTER0STATE" = "poweredOn" ]; then
    printf "%-30s %-20s %-50s\n" "$dir *" "$ocpversion" "$vmwarenotes"
  else
    printf "%-30s %-20s %-50s\n" "$dir" "$ocpversion" "$vmwarenotes"
  fi
}

selection_list=$(find /vms/clusters/ -mindepth 1 -maxdepth 1 -type d -name '*-*' \
  ! -name 'backup-20230903' \
  ! -name '*-files' \
  ! -name 'quay-*' \
  -exec basename {} \; | while read -r dir; do
    clusters "$dir"
  done)

if [ -z "$selection_list" ]; then
  tmux display-message -d 5000 "No clusters found"
  exit 0
fi

selected_entry=$(echo "$selection_list" | fzf-tmux --header=$'Cluster Name to destroy        OCP Version          Description\n'  --layout=reverse -p "100%,50%" --delimiter=' / ' --with-nth=1,2,3 | awk  '{print $1}')

if [ -z "$selected_entry" ]; then
  exit 0
fi

temp_file=$(mktemp)

tmux new-window -n "destroy: $selected_entry" "bash -c 'read -p \"Are you sure you want to destroy the cluster \\\"$selected_entry\\\"? (y/N): \" confirm; echo \$confirm > $temp_file; bash'"

while [ ! -s "$temp_file" ]; do
  sleep 1
done

confirm=$(cat "$temp_file")
rm -f "$temp_file"

if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  exit 0
fi

tmux send-keys "/usr/local/bin/destroycluster.py -i /vms/clusters/$selected_entry/$selected_entry.json -n $selected_entry" C-m

