#!/usr/bin/env bash

# Exit if not running on bastion.chiaret.to
if [ "$(hostname)" != "bastion.chiaret.to" ]; then
    echo "This script must be run on bastion.chiaret.to. Exiting."
    exit 0
fi

temp_file=$(mktemp)

tmux new-window -n "destroy: $1" "bash -c 'read -p \"Are you sure you want to destroy the cluster \\\"$1\\\"? (y/N): \" confirm; echo \$confirm > $temp_file;'"

while [ ! -s "$temp_file" ]; do
  sleep 1
done

confirm=$(cat "$temp_file")
rm -f "$temp_file"

if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  exit 0
fi

clear
read -p "Do you also want to remove DNS and certs for cluster \"$1\"? (y/N): " confirm2
if [[ "$confirm2" == "y" || "$confirm2" == "Y" ]]; then
  jq '.deleteiffailed = "true"' /vms/clusters/$1/$1.json > /vms/clusters/$1/$1.json.tmp && mv /vms/clusters/$1/$1.json.tmp /vms/clusters/$1/$1.json
else
  jq '.deleteiffailed = "false"' /vms/clusters/$1/$1.json > /vms/clusters/$1/$1.json.tmp && mv /vms/clusters/$1/$1.json.tmp /vms/clusters/$1/$1.json
fi

infra=$(jq -r '.infra' /vms/clusters/$1/$1.json)

if [[ "$infra" == "vsphere" ]]; then
    tmux send-keys "/home/lchiaret/git/openshift4-automation/run-playbooks-destroy.py $1 &" C-m
elif [[ "$infra" == "kvm" ]]; then
  tmux send-keys "ansible-playbook  -e@/vms/clusters/$1/$1.json /home/lchiaret/git/ocp4_setup_upi_kvm_ansible/destroy-cluster.yml &" C-m
fi
