#!/bin/bash

clusters() {
  local dir="$1"
  FOLDER_VMWARE="/CHIARETTO/vm/$1"
  VMMASTER0=$(govc ls "${FOLDER_VMWARE}" | grep "master-0")
  VMMASTER0STATE=$(govc vm.info -json "$VMMASTER0" | jq -r '.virtualMachines[0].runtime.powerState')
  vmwarenotes=$(jq -r '.vmwarenotes' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
  ocpversion=$(jq -r '.ocpversion' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
  if [ "$VMMASTER0STATE" = "poweredOn" ]; then
    printf "%-30s %-20s %-50s\n" "$dir *" "$ocpversion" "$vmwarenotes"
  else
    printf "%-30s %-20s %-50s\n" "$dir" "$ocpversion" "$vmwarenotes"
  fi
}

selection_list=$(find /vms/clusters/ -mindepth 1 -maxdepth 1 -type d -name '*-*' \
  ! -name 'backup-20230903' \
  ! -name '*-files' \
  ! -name 'quay-*' \
  -exec basename {} \; | while read -r dir; do
    clusters "$dir"
  done)

if [ -z "$selection_list" ]; then
  tmux display-message -d 5000 "No clusters found"
  exit 0
fi
selected_entry=$(echo "$selection_list" | fzf-tmux --header=$'Cluster Name to export         OCP Version          Description\n'  --layout=reverse -p "100%,50%" --delimiter=' / ' --with-nth=1,2,3 | awk '{print $1}')

if [ -z "$selected_entry" ]; then
  exit 0
fi

tmux new-window  -n "export: $selected_entry" "export KUBECONFIG=/vms/clusters/$selected_entry/auth/kubeconfig; bash"
