#!/usr/bin/env bash

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$HOME/.tmux/config.sh" ]; then
    source "$HOME/.tmux/config.sh"
fi

temp_file=$(mktemp)

tmux new-window -n "recreate: $1" "bash -c 'read -p \"Are you sure you want to recreate the cluster \\\"$1\\\"? (y/N): \" confirm; echo \$confirm > $temp_file;'"

while [ ! -s "$temp_file" ]; do
  sleep 1
done

confirm=$(cat "$temp_file")
rm -f "$temp_file"

if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  exit 0
fi

infra=$(jq -r '.infra' $CLUSTERS_BASE_PATH/$1/$1.json)
destroy_if_exists=$(jq -r '.destroy_if_exists' $CLUSTERS_BASE_PATH/$1/$1.json)

if [[ "$destroy_if_exists" != "true" ]]; then
  jq '.destroy_if_exists = "true"' $CLUSTERS_BASE_PATH/$1/$1.json > "$CLUSTERS_BASE_PATH/$1/${1}_tmp.json" && mv "$CLUSTERS_BASE_PATH/$1/${1}_tmp.json" "$CLUSTERS_BASE_PATH/$1/$1.json"
fi 

if [[ "$infra" == "vsphere" ]]; then
  if [ "$(hostname)" = "bastion.chiaret.to" ]; then
      tmux send-keys "nohup /home/lchiaret/git/openshift4-automation/run-playbooks-recreate.py '$1' > /tmp/nohup-recreate.out 2>&1 &" C-m
  else
      tmux send-keys "ssh -t lchiaret@bastion.aap.chiaret.to \"nohup /home/lchiaret/git/openshift4-automation/run-playbooks-recreate.py '$1' > /tmp/nohup-recreate.out 2>&1 &\" " C-m
  fi

session_name="recreate-$1"

elif [[ "$infra" == "kvm" ]]; then
  tmux has-session -t "$session_name" 2>/dev/null && tmux kill-session -t "$session_name"; tmux new-session -d -s "$session_name"; tmux switch-client -t "$session_name"; tmux send-keys -t "$session_name" "ansible-playbook -i localhost -e \"clustername=$clustername\" -e \"@$file\" $ANSIBLE_PLAYBOOK_KVM_PATH/create-cluster-upi-kvm-modular.yaml" C-m
fi
