#!/bin/bash

selection_list=$(find /vms/clusters/ -mindepth 1 -maxdepth 1 -type d -name '*-*' \
  ! -name 'backup-20230903' \
  ! -name '*-files' \
  ! -name 'quay-*' \
  -exec basename {} \; | while read -r dir; do
    vmwarenotes=$(jq -r '.vmwarenotes' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
    echo "$dir / $vmwarenotes"
  done)

selected_entry=$(echo "$selection_list" | fzf-tmux --header="Select the clustername to start the virtual machines:" --layout=reverse -p "50%,50%" --delimiter=' / ' --with-nth=1,2 | awk -F ' / ' '{print $1}')

if [ -z "$selected_entry" ]; then
#  echo "No directory selected."
	  exit 0
fi

tmux new-window -n "start: $selected_entry" "cd /vms/clusters/$selected_entry/ && ./startvms.sh;bash"
