#!/bin/bash

selection_list=$(find /vms/clusters/ -mindepth 1 -maxdepth 1 -type d -name '*-*' \
  ! -name 'backup-20230903' \
  ! -name '*-files' \
  ! -name 'quay-*' \
  -exec basename {} \; | while read -r dir; do
    vmwarenotes=$(jq -r '.vmwarenotes' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
    ocpversion=$(jq -r '.ocpversion' "/vms/clusters/$dir/$dir.json" 2>/dev/null || echo "No notes")
    printf "%-30s %-20s %-50s\n" "$dir" "$ocpversion" "$vmwarenotes"
  done)

if [ -z "$selection_list" ]; then
  tmux display-message -d 5000 "No clusters found"
  exit 0
fi

selected_entry=$(echo "$selection_list" | fzf-tmux --header=$'Cluster Name to start          OCP Version          Description\n' --layout=reverse -p "38%,50%" --delimiter=' / ' --with-nth=1,2,3 | awk -F ' / ' '{print $1}')

if [ -z "$selected_entry" ]; then
  exit 0
fi

tmux new-window -n "start: $selected_entry" "cd /vms/clusters/$selected_entry/ && ./startvms.sh;bash"
