#!/usr/bin/env bash

function error_exit {
    echo "ERROR: $1" >&2
    exit 1
}

clustername=$1

#echo "Checking OpenShift cluster $clustername status..."
oc whoami &> /dev/null
if [ $? -ne 0 ]; then
    error_exit "You are not connected to any OpenShift cluster or the 'oc' command is not available."
fi

oc get clusterversion version --output=jsonpath='{.status.desired.version}' &> /dev/null

CURRENT_VERSION=$(oc get clusterversions version --output=jsonpath='{.status.desired.version}')
CURRENT_CHANNEL=$(oc get clusterversions version --output=jsonpath='{.spec.channel}')
CLUSTER_NAME=$(oc whoami --show-server | awk -F'.' '{print $2}')
# echo "Current cluster version: $CURRENT_VERSION"
# echo "Current cluster channel: $CURRENT_CHANNEL"

if [ "$CLUSTER_NAME" != "$clustername" ]; then
    error_exit "The connected cluster '$CLUSTER_NAME' does not match the selected cluster '$clustername'"
fi

UPGRADE_STATUS=$(oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Progressing")].status}')
if [ "$UPGRADE_STATUS" == "True" ]; then
    error_exit "An update is already in progress. Please wait until it completes or has failed."
fi

CHANNELS=$(oc get clusterversion version -o json | jq -r '.status.desired.channels[]')
if [ -z "$CHANNELS" ]; then
    error_exit "Could not retrieve update channels."
fi

SELECTED_CHANNEL=$(echo "$CHANNELS" | fzf-tmux --prompt="Channel > " -p "40%,40%" --layout=reverse )

if [ -z "$SELECTED_CHANNEL" ]; then
    error_exit "Channel selection cancelled. Exiting."
    exit 0
fi

oc adm upgrade channel "$SELECTED_CHANNEL"

AVAILABLE_VERSIONS=$(oc get clusterversion version -o json | jq -e -r '.status.availableUpdates[].version' 2>/dev/null | sort -V || echo "")

if [ -z "$AVAILABLE_VERSIONS" ]; then
    error_exit "No valid versions found for channel '$SELECTED_CHANNEL'. Try another channel."
fi

SELECTED_VERSION=$(echo "$AVAILABLE_VERSIONS" | fzf-tmux --header="Available versions for channel '$SELECTED_CHANNEL'" --layout=reverse -h 40 -p "40%,40%")

if [ -z "$SELECTED_VERSION" ]; then
    error_exit "Version selection cancelled. Exiting."
    exit 0
fi

echo "Selected version: $SELECTED_VERSION"
echo ""

read -p "Do you really want to start the update to version $SELECTED_VERSION on channel $SELECTED_CHANNEL? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Update cancelled. Exiting."
    exit 0
fi

echo "Starting OpenShift cluster update to version $SELECTED_VERSION on channel $SELECTED_CHANNEL..."
oc adm upgrade --to="$SELECTED_VERSION"
if [ $? -ne 0 ]; then
    error_exit "Failed to initiate the update. Check the error messages above."
fi

yes | tmuxp load /vms/clusters/$clustername/upgrade-tmuxp.yaml