#!/usr/bin/env bash

error_exit() {
    echo -e "ERROR: $1" >&2
    exit 1
}

timeout 2s oc whoami &> /dev/null || error_exit "You are not connected to any OpenShift cluster or the 'oc' command is not available."

clustername=$1

CURRENT_VERSION=$(oc get clusterversions version -o jsonpath='{.status.desired.version}')
CURRENT_CHANNEL=$(oc get clusterversions version -o jsonpath='{.spec.channel}')
CLUSTER_NAME=$(oc whoami --show-server | awk -F'.' '{print $2}')

[ "$CLUSTER_NAME" != "$clustername" ] && error_exit "The connected cluster '$CLUSTER_NAME' does not match the selected cluster '$clustername'"

UPGRADE_STATUS=$(oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Progressing")].status}')
[ "$UPGRADE_STATUS" == "True" ] && error_exit "An update is already in progress. Please wait until it completes or has failed."

CHANNELS=$(oc get clusterversion version -o json | jq -r '.status.desired.channels[]')
[ -z "$CHANNELS" ] && error_exit "Could not retrieve update channels."

SELECTED_CHANNEL=$(echo -e "$CHANNELS" | sort | fzf-tmux \
    --header=$'
----------------------------------------- Update path tool ---------------------------------------------------
|                                                                                                            |
|  [Enter]....Select the channel                                                                             |
|  [Esc]......Exit                                                                                           |
|                                                                                                            |
--------------------------------------------------------------------------------------------------------------\n\n' \
    --layout=reverse \
    --border-label=" chiaret.to " \
    --border-label-pos=center \
    -h 40 -p "55%,46%" \
    --no-input \
    --no-sort \
    --color=fg:#ffffff,bg:#1d2021,hl:#d8a657 \
    --color=fg+:#a9b665,bg+:#1d2021,hl+:#a9b665
    )

[ -z "$SELECTED_CHANNEL" ] && error_exit "Channel selection cancelled. Exiting."

if [ "$SELECTED_CHANNEL" != "$CURRENT_CHANNEL" ]; then
    UPGRADABLE_STATUS=$(oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Upgradeable")].status}')
    if [ "$UPGRADABLE_STATUS" == "False" ]; then
        REASON=$(oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Upgradeable")].reason}')
        MESSAGE=$(oc get clusterversion version -o jsonpath='{.status.conditions[?(@.type=="Upgradeable")].message}')
        echo "Cluster is not upgradable"
        echo "Reason: $REASON"
        error_exit "Message: $MESSAGE"
    fi
    oc adm upgrade channel $SELECTED_CHANNEL
    sleep 3 # Wait for the channel to be set  
fi

AVAILABLE_VERSIONS=$(oc get clusterversion version -o json | jq -e -r '.status.availableUpdates[].version' 2>/dev/null | sort -V || echo "")

if [ -z "$AVAILABLE_VERSIONS" ]; then
    oc adm upgrade channel "$CURRENT_CHANNEL"
    error_exit "No valid versions found for channel '$SELECTED_CHANNEL'. Try another channel."
fi

SELECTED_VERSION=$(echo "$AVAILABLE_VERSIONS" | fzf-tmux \
    --header="Available versions for channel '$SELECTED_CHANNEL'" \
    --layout=reverse \
    -h 40 -p "40%,40%" \
    --border-label=" chiaret.to " \
    --border-label-pos=center \
    --color=fg:#ffffff,bg:#1d2021,hl:#d8a657 \
    --color=fg+:#a9b665,bg+:#1d2021,hl+:#a9b665
)
if [ -z "$SELECTED_VERSION" ]; then
    oc adm upgrade channel "$CURRENT_CHANNEL"
    echo "Version selection cancelled. Exiting."
    exit 0
fi

echo "Selected version: $SELECTED_VERSION"
echo ""

read -p "Do you really want to start the update to version $SELECTED_VERSION on channel $SELECTED_CHANNEL? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Update cancelled. Exiting."
    oc adm upgrade channel "$CURRENT_CHANNEL"
    exit 0
fi

echo "Starting OpenShift cluster update to version $SELECTED_VERSION on channel $SELECTED_CHANNEL..."
oc adm upgrade --to="$SELECTED_VERSION"
if [ $? -ne 0 ]; then
    oc adm upgrade channel "$CURRENT_CHANNEL"
    error_exit "Failed to initiate the update. Check the error messages above."
fi

CURRENT_VERSION=$(oc get clusterversion -o jsonpath='{.items[0].status.desired.version}')
sed -i "s/$CURRENT_VERSION/$SELECTED_VERSION/" /vms/clusters/$clustername/$clustername.json

yes | tmuxp load /vms/clusters/$clustername/upgrade-tmuxp.yaml