#!/usr/bin/env bash

#files=$(find /vms/clusters/variables-files/ -type f -exec basename {} \; | sed 's/^ansible-vars-//' | sed 's/\.json$//')


actions="- Baremetal IPI 3-node cluster
- Baremetal IPI 4-node cluster
- Baremetal IPI 5-node cluster
- Baremetal UPI Single node OpenShift
- Baremetal UPI Single node OpenShift with ODF nodes
- None UPI 3-node cluster
- None UPI 3-node cluster with 'ODF'
- vSphere IPI 3-node cluster
- vSphere UPI 3-node cluster"


selected_file=$(echo -e "$actions" | sort | fzf-tmux \
    --header=$'
----------------------------------------- Create cluster -----------------------------------------------------
|                                                                                                            |
|  [Enter]....Edit the cluster configuration                                                                 |
|  [Esc]......Exit                                                                                           |
|                                                                                                            |
--------------------------------------------------------------------------------------------------------------\n\n' \
    --layout=reverse \
    --border-label=" chiaret.to " \
    --border-label-pos=center \
    -h 40 -p "55%,46%" \
    --no-input \
    --no-sort \
    --color=fg:#ffffff,bg:#1d2021,hl:#d8a657 \
    --color=fg+:#a9b665,bg+:#1d2021,hl+:#a9b665 \
    )


variablesfile=$(echo "$selected_file" | tail -n1)

if [ -n "$selected_file" ]; then
    case "$variablesfile" in
        "- Baremetal IPI 3-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-ipi-3node-baremetal.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- Baremetal IPI 4-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-ipi-4node-baremetal.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- Baremetal IPI 5-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-ipi-5node-baremetal.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- Baremetal UPI Single node OpenShift")
            file="/vms/clusters/variables-files/ansible-vars-sno-baremetal.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- Baremetal UPI Single node OpenShift with ODF nodes")
            file="/vms/clusters/variables-files/ansible-vars-sno-odf-baremetal.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- None UPI 3-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-upi-3node-none.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- None UPI 3-node cluster with 'ODF'")
            file="/vms/clusters/variables-files/ansible-vars-upi-3node-odf-none.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- None UPI Single node cluster")
            file="/vms/clusters/variables-files/ansible-vars-upi-sno-none.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- None UPI Single node cluster with 'OCP Virt'")
            file="/vms/clusters/variables-files/ansible-vars-upi-sno-ocpvirt-none.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- None UPI Single node cluster with 'ODF'")
            file="/vms/clusters/variables-files/ansible-vars-upi-sno-odf-none.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- vSphere IPI 3-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-ipi-3node-vsphere.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- vSphere UPI 3-node cluster")
            file="/vms/clusters/variables-files/ansible-vars-upi-3node-vsphere.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- vSphere UPI Single node cluster")
            file="/vms/clusters/variables-files/ansible-vars-upi-sno-vsphere.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
        "- vSphere IPI Single node cluster")
            file="/vms/clusters/variables-files/ansible-vars-ipi-sno.json"
            tmux new-window -n "vim $file" "vim $file; tmux wait-for -S vim-done"
            tmux wait-for vim-done
            ;;
    esac
fi

if [ -z "$selected_file" ]; then
    tmux display -d 3000 "No file selected"
    exit 0
fi