set bg=dark         " dark bg when console background is black
set tabstop=4       " (ts) width (in spaces) that a <tab> is displayed as
set softtabstop=4   " (sts) makes spaces feel like tabs (like deleting)
set shiftwidth=4    " (sw) width (in spaces) used in each step of autoindent (aswell as << and >>)
set autoindent      " (ai) turn on auto-indenting (great for programers)
set expandtab       " (et) expand tabs to spaces (use :retab to redo entire file)

nnoremap v <c-v> " remap `v` to `Ctrl-v`
autocmd FileType yaml setlocal ai et ts=2 sts=2 sw=2    "Only when file is an yaml format

" This is to rename-window when file is opened by vim
if exists('$TMUX')
    autocmd BufEnter * let &titlestring = expand("%:t")
    set title
endif

" This is to use vim modules using Vundle
if !empty(glob("~/.vim/bundle/Vundle.vim"))
    nnoremap <C-space> <tab>
    set nocompatible              " be iMproved, required
    filetype off                  " required <<========== We can turn it on later
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'davidhalter/jedi-vim'
    call vundle#end()            " required
    filetype plugin indent on    " required
    set completeopt-=preview
endif
