set bg=dark         " dark bg when console background is black
set tabstop=4       " (ts) width (in spaces) that a <tab> is displayed as
set softtabstop=4   " (sts) makes spaces feel like tabs (like deleting)
set shiftwidth=4    " (sw) width (in spaces) used in each step of autoindent (aswell as << and >>)
set autoindent      " (ai) turn on auto-indenting (great for programers)
set expandtab       " (et) expand tabs to spaces (use :retab to redo entire file)
nnoremap v <c-v> " remap `v` to `Ctrl-v`

" This is to rename-window when file is opened by vim
if exists('$TMUX')
    autocmd BufEnter * let &titlestring = expand("%:t")
    set title
endif

" This is to use vim modules using Vundle
if !empty(glob("~/.vim/bundle/Vundle.vim"))
    nnoremap <C-space> <tab>
    set nocompatible              " be iMproved, required
    filetype off                  " required <<========== We can turn it on later
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'davidhalter/jedi-vim'
    call vundle#end()            " required
    filetype plugin indent on    " required
    "set completeopt-=preview
    set completeopt=noselect,menuone
    hi Pmenu ctermbg=black ctermfg=white
    hi PmenuSel ctermbg=blue ctermfg=white
endif

" Python Files
autocmd FileType python setlocal nu
autocmd FileType python inoremap ( ()<Left>
autocmd FileType python inoremap { {}<Left>
autocmd FileType python inoremap [ []<Left>
autocmd FileType python inoremap ' ''<Left>
autocmd FileType python inoremap " ""<Left>
" Execute script with no parameters
autocmd FileType python nnoremap <buffer> <F5> :exec '!clear && python' shellescape(@%, 1)<cr>
" Execute script with parameters
autocmd FileType python nnoremap <buffer> <F6> :exec '!clear && python %' 
autocmd FileType python set pumheight=15

" YAML Files
autocmd FileType yaml setlocal ai et ts=2 sts=2 sw=2    "Only when file is an yaml format
